### ISSUE TITLE
Cherry style stabs?

### ISSUE THREAD

**Issue by 9fm** [mimnix/mimkb-83#2]
Can we get cherry style stabs? I love the design but i absolutely hate costar stabs.
Thanks

**Comment by mimnix** [comment]
Hi! Of course, you can get them, just set the property `stabilizer_type` to `cherry_stabilizer` in the file `model/keycaps/KeyV2/src/settings.scad` so that the model (keys.scad) will be rendered accordingly.

```
// Enable stabilizer stems, to hold onto your cherry or costar stabilizers
$stabilizer_type = "costar_stabilizer"; // [costar_stabilizer, cherry_stabilizer, disable]
```

**Comment by 9fm** [comment]
tysm!!!
